name: BetterPhotos
options:
  bundleIdPrefix: com.betterphotos
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: BetterPhotos
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    ENABLE_HARDENED_RUNTIME: NO
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""

targets:
  BetterPhotos:
    type: application
    platform: macOS
    sources:
      - path: BetterPhotos/Sources
        type: group
    settings:
      base:
        INFOPLIST_FILE: BetterPhotos/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.betterphotos.app
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        ENABLE_APP_SANDBOX: NO
        MACOSX_DEPLOYMENT_TARGET: "14.0"
    entitlements:
      path: BetterPhotos/BetterPhotos.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.automation.apple-events: true
        com.apple.security.personal-information.photos-library: true
